apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: test
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: sample-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
